var annotated_dup =
[
    [ "axi_dma", "namespaceaxi__dma.html", [
      [ "block_template", "structaxi__dma_1_1block__template.html", "structaxi__dma_1_1block__template" ],
      [ "mm2s_curdesc_t", "structaxi__dma_1_1mm2s__curdesc__t.html", "structaxi__dma_1_1mm2s__curdesc__t" ],
      [ "mm2s_dmacr_t", "structaxi__dma_1_1mm2s__dmacr__t.html", "structaxi__dma_1_1mm2s__dmacr__t" ],
      [ "mm2s_dmasr_t", "structaxi__dma_1_1mm2s__dmasr__t.html", "structaxi__dma_1_1mm2s__dmasr__t" ],
      [ "mm2s_length_t", "structaxi__dma_1_1mm2s__length__t.html", "structaxi__dma_1_1mm2s__length__t" ],
      [ "mm2s_taildesc_t", "structaxi__dma_1_1mm2s__taildesc__t.html", "structaxi__dma_1_1mm2s__taildesc__t" ],
      [ "s2mm_curdesc_t", "structaxi__dma_1_1s2mm__curdesc__t.html", "structaxi__dma_1_1s2mm__curdesc__t" ],
      [ "s2mm_dmacr_t", "structaxi__dma_1_1s2mm__dmacr__t.html", "structaxi__dma_1_1s2mm__dmacr__t" ],
      [ "s2mm_dmasr_t", "structaxi__dma_1_1s2mm__dmasr__t.html", "structaxi__dma_1_1s2mm__dmasr__t" ],
      [ "s2mm_length_t", "structaxi__dma_1_1s2mm__length__t.html", "structaxi__dma_1_1s2mm__length__t" ],
      [ "s2mm_taildesc_t", "structaxi__dma_1_1s2mm__taildesc__t.html", "structaxi__dma_1_1s2mm__taildesc__t" ],
      [ "sg_ctl_t", "structaxi__dma_1_1sg__ctl__t.html", "structaxi__dma_1_1sg__ctl__t" ]
    ] ],
    [ "axi_vdma", "namespaceaxi__vdma.html", [
      [ "block_template", "structaxi__vdma_1_1block__template.html", "structaxi__vdma_1_1block__template" ],
      [ "mm2s_frmdly_stride_t", "structaxi__vdma_1_1mm2s__frmdly__stride__t.html", "structaxi__vdma_1_1mm2s__frmdly__stride__t" ],
      [ "mm2s_hsize_t", "structaxi__vdma_1_1mm2s__hsize__t.html", "structaxi__vdma_1_1mm2s__hsize__t" ],
      [ "mm2s_reg_index_t", "structaxi__vdma_1_1mm2s__reg__index__t.html", "structaxi__vdma_1_1mm2s__reg__index__t" ],
      [ "mm2s_vdmacr_t", "structaxi__vdma_1_1mm2s__vdmacr__t.html", "structaxi__vdma_1_1mm2s__vdmacr__t" ],
      [ "mm2s_vdmasr_t", "structaxi__vdma_1_1mm2s__vdmasr__t.html", "structaxi__vdma_1_1mm2s__vdmasr__t" ],
      [ "mm2s_vsize_t", "structaxi__vdma_1_1mm2s__vsize__t.html", "structaxi__vdma_1_1mm2s__vsize__t" ],
      [ "park_ptr_reg_t", "structaxi__vdma_1_1park__ptr__reg__t.html", "structaxi__vdma_1_1park__ptr__reg__t" ],
      [ "s2mm_frmdly_stride_t", "structaxi__vdma_1_1s2mm__frmdly__stride__t.html", "structaxi__vdma_1_1s2mm__frmdly__stride__t" ],
      [ "s2mm_hsize_t", "structaxi__vdma_1_1s2mm__hsize__t.html", "structaxi__vdma_1_1s2mm__hsize__t" ],
      [ "s2mm_reg_index_t", "structaxi__vdma_1_1s2mm__reg__index__t.html", "structaxi__vdma_1_1s2mm__reg__index__t" ],
      [ "s2mm_vdma_irq_mask_t", "structaxi__vdma_1_1s2mm__vdma__irq__mask__t.html", "structaxi__vdma_1_1s2mm__vdma__irq__mask__t" ],
      [ "s2mm_vdmacr_t", "structaxi__vdma_1_1s2mm__vdmacr__t.html", "structaxi__vdma_1_1s2mm__vdmacr__t" ],
      [ "s2mm_vdmasr_t", "structaxi__vdma_1_1s2mm__vdmasr__t.html", "structaxi__vdma_1_1s2mm__vdmasr__t" ],
      [ "s2mm_vsize_t", "structaxi__vdma_1_1s2mm__vsize__t.html", "structaxi__vdma_1_1s2mm__vsize__t" ],
      [ "vdma_version_t", "structaxi__vdma_1_1vdma__version__t.html", "structaxi__vdma_1_1vdma__version__t" ]
    ] ],
    [ "udmaio", "namespaceudmaio.html", [
      [ "ConcurrentQueue", "classudmaio_1_1_concurrent_queue.html", "classudmaio_1_1_concurrent_queue" ],
      [ "DataHandlerAbstract", "classudmaio_1_1_data_handler_abstract.html", "classudmaio_1_1_data_handler_abstract" ],
      [ "DataHandlerSync", "classudmaio_1_1_data_handler_sync.html", "classudmaio_1_1_data_handler_sync" ],
      [ "DmaBufferAbstract", "classudmaio_1_1_dma_buffer_abstract.html", "classudmaio_1_1_dma_buffer_abstract" ],
      [ "FpgaMemBufferOverAxi", "classudmaio_1_1_fpga_mem_buffer_over_axi.html", "classudmaio_1_1_fpga_mem_buffer_over_axi" ],
      [ "FpgaMemBufferOverXdma", "classudmaio_1_1_fpga_mem_buffer_over_xdma.html", "classudmaio_1_1_fpga_mem_buffer_over_xdma" ],
      [ "FrameFormat", "classudmaio_1_1_frame_format.html", "classudmaio_1_1_frame_format" ],
      [ "HwAccessor", "classudmaio_1_1_hw_accessor.html", "classudmaio_1_1_hw_accessor" ],
      [ "HwAccessorAxi", "classudmaio_1_1_hw_accessor_axi.html", "classudmaio_1_1_hw_accessor_axi" ],
      [ "HwAccessorMmap", "classudmaio_1_1_hw_accessor_mmap.html", "classudmaio_1_1_hw_accessor_mmap" ],
      [ "HwAccessorMock", "classudmaio_1_1_hw_accessor_mock.html", "classudmaio_1_1_hw_accessor_mock" ],
      [ "HwAccessorXdma", "classudmaio_1_1_hw_accessor_xdma.html", "classudmaio_1_1_hw_accessor_xdma" ],
      [ "Logger", "structudmaio_1_1_logger.html", "structudmaio_1_1_logger" ],
      [ "RegAccessorArray", "classudmaio_1_1_reg_accessor_array.html", "classudmaio_1_1_reg_accessor_array" ],
      [ "RegAccessorArray< C, offset, 0, 0 >", "classudmaio_1_1_reg_accessor_array_3_01_c_00_01offset_00_010_00_010_01_4.html", "classudmaio_1_1_reg_accessor_array_3_01_c_00_01offset_00_010_00_010_01_4" ],
      [ "RegAccessorArrayElement", "classudmaio_1_1_reg_accessor_array_element.html", "classudmaio_1_1_reg_accessor_array_element" ],
      [ "RegAccessorBase", "classudmaio_1_1_reg_accessor_base.html", "classudmaio_1_1_reg_accessor_base" ],
      [ "UDmaBuf", "classudmaio_1_1_u_dma_buf.html", "classudmaio_1_1_u_dma_buf" ],
      [ "UioAxiDmaIf", "classudmaio_1_1_uio_axi_dma_if.html", "classudmaio_1_1_uio_axi_dma_if" ],
      [ "UioAxiVdmaIf", "classudmaio_1_1_uio_axi_vdma_if.html", "classudmaio_1_1_uio_axi_vdma_if" ],
      [ "UioConfigBase", "classudmaio_1_1_uio_config_base.html", "classudmaio_1_1_uio_config_base" ],
      [ "UioConfigUio", "classudmaio_1_1_uio_config_uio.html", "classudmaio_1_1_uio_config_uio" ],
      [ "UioConfigXdma", "classudmaio_1_1_uio_config_xdma.html", "classudmaio_1_1_uio_config_xdma" ],
      [ "UioDeviceLocation", "classudmaio_1_1_uio_device_location.html", "classudmaio_1_1_uio_device_location" ],
      [ "UioIf", "classudmaio_1_1_uio_if.html", "classudmaio_1_1_uio_if" ],
      [ "UioMemSgdma", "classudmaio_1_1_uio_mem_sgdma.html", "classudmaio_1_1_uio_mem_sgdma" ],
      [ "UioRegion", "structudmaio_1_1_uio_region.html", "structudmaio_1_1_uio_region" ]
    ] ],
    [ "AxiTrafficGenLfsr", "class_axi_traffic_gen_lfsr.html", "class_axi_traffic_gen_lfsr" ],
    [ "DataHandlerPrint", "class_data_handler_print.html", "class_data_handler_print" ],
    [ "UioGpioStatus", "class_uio_gpio_status.html", "class_uio_gpio_status" ],
    [ "UioTrafficGen", "class_uio_traffic_gen.html", "class_uio_traffic_gen" ]
];