from __future__ import annotations
import bitstruct as bitstruct
__all__ = ['UioReg', 'UioRegTest', 'bitstruct']
class UioReg:
    def __getattr__(self, name):
        ...
    def __init__(self, intf, offs, fields = None):
        ...
    def __setattr__(self, name, value):
        ...
    def rd(self):
        ...
    def wr(self, val = None):
        ...
class UioRegTest:
    def __init__(self):
        ...
    def _rd32(self, offs):
        ...
    def _wr32(self, offs, val):
        ...
    def test(self):
        ...
